// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chnntgvhvimbahjwbuml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNobm50Z3ZodmltYmFoandidW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwMDUxMTUsImV4cCI6MjA0OTU4MTExNX0.Q24tMM5CcOR4iZTvVrEsW6mz-Z29QrheJC0BrJJt8UQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);